senzing-garage/g2-python

.github/CODEOWNERS
=> #2 Add CODEOWNERS

CHANGELOG.md, bin/01-user-variables.sh.template, bin/05-commit-repositories.md, bin/13-create-g2-python-version.md, g2/python/demo/truth/truthset-person-v1-set1.sh, g2/python/demo/truth/truthset-person-v1-set2.sh
=> Issue 2.dockter.2

.github/CODEOWNERS
=> #2 Update owners

README.md, bin/13-create-g2-python-version.md, bin/github-submodule-versions.py, bin/update-submodules.sh
=> Issue 83.dockter.1

CHANGELOG.md, bin/05-commit-repositories.md, bin/07-submodules.sh, bin/11-check-files.sh, bin/13-create-g2-python-version.md
=> SenzingAPI 2.8.1

.gitmodules
=> #105 Delete submodules

CHANGELOG.md
=> #100 Updates for new Senzing releases

bin/copy-submodules-to-g2-python.sh
=> #118 Add script

g2/python/governor_postgres_xid.py
=> #121 Migrate G2DBException

g2/python/governor_postgres_xid.py
=> #123 Fix PEP-8 issues

.project, CONTRIBUTING.md, README.md, bin/github-submodule-versions.py
=> Issue 126.dockter.1

.gitmodules, g2/python/G2Command.py, g2/python/G2ConfigTool.py, g2/python/G2Explorer.py, g2/python/G2Export.py, g2/python/G2IniParams.py, g2/python/G2Loader.py, g2/python/G2SetupConfig.py, g2/python/G2Snapshot.py
=> Issue 141.jae.1

g2/python/G2CreateProject.py, g2/python/G2UpdateProject.py
#143 Update submodules, after the removal of g2rst.jar.
=> #143 Update submodules, after the removal of g2rst.jar.

g2/python/G2Command.py
#146 Update the G2Command submodule to the most current version.
=> #146 Update the G2Command submodule to the most current version.

g2/python/G2Loader.py
#150 Update to the latest G2Loader module.
=> #150 Update to the latest G2Loader module.

g2/python/governor_postgres_xid.py
=> Small fixes to governor_postgres_xid.py

g2/python/G2CreateProject.py
#156 Update to most recent g2createproject submodule.
=> #156 Update to most recent g2createproject submodule.

g2/python/G2Command.py, g2/python/G2ConfigTool.py, g2/python/G2Loader.py
#159 Update the submodules to the current versions.
=> #159 Update the submodules to the current versions.

g2/python/G2Snapshot.py
Update the G2Snapshot submodule to it's current version.
=> #162 Update the G2Snapshot submodule to the latest version.

g2/python/governor_postgres_xid.py
=> Issue 164 - fix raise messages

.gitmodules
=> #170 branch with specific name

.gitmodules
=> Issue 170.dockter.4

README.md
=> #174 Update links

g2/python/G2Loader.py
Issue number: #176
Actions taken:
```console
git pull --recurse-submodules
git checkout issue-176.dockter.1 
cd g2loader
git checkout main
cd ..
git commit -a -m "#176 Update submodules"
git push
```
=> #176 Update submodules

g2/python/G2Command.py
=> #185 Update to the most recent version of g2command submodule.

.github/linters/.yaml-lint.yml, .github/workflows/add-labels-standardized.yaml, .github/workflows/add-to-project-g2-python-dependabot.yaml, .github/workflows/add-to-project-g2-python.yaml, .github/workflows/lint-workflows.yaml
Issue number: senzing-factory/build-resources#69
=> senzing-factory/build-resources#69 add linting

.github/workflows/add-labels-standardized.yaml, .github/workflows/add-to-project-g2-python-dependabot.yaml, .github/workflows/add-to-project-g2-python.yaml
Issue number: senzing-factory/build-resources#179
=> senzing-factory/build-resources#179 add slack notifications
